### PR TITLE
Upgrade opam to version 2.1

### PR DESCRIPTION
**Pull request by bikallem**
This PR upgrades the tezos repo to use opam 2.1. With opam 2.1 we don't need opam package depext since it is included with opam 2.1 itself. Additionally, `opam install --yes opam-depext` errors in 2.1 since the package is not available for 2.1. Therefore the invocation is removed in `install_build_deps.sh`

Additionally, the PR also adds support to building/developing tezos in NixOS 21.11 and over. For this it adds 2 files 
(flake.nix, flake.lock). Other OSes are unaffected by these two files.

### CODE REVIEW

**Review by Sudha247 — APPROVED** [review]
Thanks @bikallem! The PR looks good.

Can you please update the GitHub Actions CI to install opam 2.1: https://github.com/ocaml-multicore/tezos/blob/4.12.0%2Bdomains/ci.Dockerfile#L24

**Comment by bikallem** [comment]
I had some issues in `Step 22/22 : RUN opam exec -- make test-unit` when attempting to build `ci.Dockerfile` locally via `docker build -f ci.Dockerfile .`. The issue was with the permission for `test_results` folder. 

I have added some remedial steps to address this. However, it seems this is not required in the CI environment. Therefore I have disabled it for now. I still need to investigate why the docker build `make test-unit` step fails locally.

Edit: The CI doesn't seem to be triggered on opening this PR as I am unable to find the workflow run in the 'Actions' tab.

**Comment by bikallem** [comment]
@Sudha247 This is ready to merge I think.

**Comment by Sudha247** [comment]
Merging.

**Pull request merged**
