### PR TITLE
fix make build-deps, fix nixos support

### PR DESCRIPTION
**Pull request by bikallem**
This PR fixes `make build-deps/build-dev-deps`. `conf-perl` is no longer required upstream and is thus removed from tezos-opam-repository.

`tezos-opam-repository` also points to the latest commit now.

### CODE REVIEW

**Comment by Sudha247** [comment]
Are the flake.* files not required anymore for nixos?

**Comment by bikallem** [comment]
> Are the flake.* files not required anymore for nixos?

Oops, good catch. They are replaced by shell.nix and .envrc. commit ^^

**Comment by bikallem** [comment]
@Sudha247 this is ready for review. I have squashed the commits together for easy git history

**Comment by Sudha247** [comment]
Great! Just one question from me: Is it right that `.envrc` file doesn't affect other environments apart from nix?

**Comment by bikallem** [comment]
Yes, `.envrc` will not affect your dev/pc environment unless you opt-in manually by issuing `direnv allow`. `direnv` (https://github.com/direnv/) is needed to be installed. The `.envrc` basically does the following when I `cd` into my local tezos repo dir. 
-  initializes a nixos dev shell 
-  execute `eval $(opam env)` so that local opam switch is selected automatically

**Pull request merged**
